import { useState, useEffect } from 'react';
import UrgencySelector from '../components/UrgencySelector';
import ChecklistItem from '../components/ChecklistItem';
import SkeletonLoader from '../components/SkeletonLoader';
import { useToast } from '../components/Toast';
import { getFeatureAIResponse, SYSTEM_PROMPTS, buildChecklistPrompt } from '../lib/ai';
import { fallbackResponses } from '../lib/fallbacks';
import { getChecklistProgress, setChecklistProgress } from '../lib/storage';
import jsPDF from 'jspdf';

export default function PreConsultChecklist() {
  const [urgency, setUrgency] = useState('');
  const [condition, setCondition] = useState('');
  const [questions, setQuestions] = useState([]);
  const [checked, setChecked] = useState([]);
  const [loading, setLoading] = useState(false);
  const addToast = useToast();

  useEffect(() => {
    const saved = getChecklistProgress();
    if (saved && saved.questions?.length) {
      setQuestions(saved.questions);
      setChecked(saved.checked || []);
      setCondition(saved.condition || '');
      setUrgency(saved.urgency || '');
      addToast('Previous checklist restored');
    }
  }, []);

  useEffect(() => {
    if (questions.length > 0) {
      setChecklistProgress({ questions, checked, condition, urgency });
    }
  }, [checked]);

  const parseQuestions = (text) => {
    return text.split('\n')
      .filter(line => /^\d+\./.test(line.trim()))
      .map(line => line.trim().replace(/^\d+\.\s*/, ''));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!condition.trim()) { addToast('Please describe your condition', 'error'); return; }
    if (!urgency) { addToast('Please select an urgency level', 'error'); return; }
    setLoading(true);
    setQuestions([]);
    setChecked([]);
    try {
      const { content, source } = await getFeatureAIResponse({
        systemPrompt: SYSTEM_PROMPTS.checklist,
        userPrompt: buildChecklistPrompt(urgency, condition),
        fallbackResponse: () => fallbackResponses.checklist(urgency, condition),
        minimumLength: 180,
        relevanceTerms: ['1.', '2.', 'doctor', 'condition'],
      });
      const parsed = parseQuestions(content);
      if (parsed.length >= 5) {
        setQuestions(parsed);
        setChecked(new Array(parsed.length).fill(false));
      } else {
        const fallback = parseQuestions(fallbackResponses.checklist(urgency, condition));
        setQuestions(fallback);
        setChecked(new Array(fallback.length).fill(false));
      }
      if (source === 'fallback') {
        addToast('Using offline checklist — for best results, add a Gemini API key', 'warning');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleCheck = (index, value) => {
    const next = [...checked];
    next[index] = value;
    setChecked(next);
  };

  const checkedCount = checked.filter(Boolean).length;

  const copyAll = () => {
    const text = questions.map((q, i) => `${i + 1}. ${q}`).join('\n');
    navigator.clipboard.writeText(text);
    addToast('Checklist copied');
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setTextColor(186, 25, 33);
    doc.text('HealthID — Pre-Consultation Checklist', 20, 25);
    doc.setFontSize(11);
    doc.setTextColor(26, 6, 8);
    if (condition) {
      doc.text(`Condition: ${condition.substring(0, 80)}`, 20, 40);
    }
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 20, 50);
    doc.setFontSize(10);
    let y = 65;
    questions.forEach((q, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      const lines = doc.splitTextToSize(`${i + 1}. ${q}`, 170);
      doc.text(lines, 20, y);
      y += lines.length * 6 + 4;
    });
    doc.setFontSize(8);
    doc.setTextColor(154, 100, 104);
    doc.text('Generated by HealthID — See Clearly. Choose Right.', 20, 285);
    doc.save('HealthID-Checklist.pdf');
    addToast('Checklist downloaded as PDF');
  };

  return (
    <div>
      <div className="bg-primary text-white py-10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="font-display text-2xl sm:text-3xl font-bold">Know What to Ask Before You Go</h1>
          <p className="mt-2 text-sm opacity-90">Never leave a consultation confused again.</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        <UrgencySelector value={urgency} onChange={setUrgency} />

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-semibold text-text-primary mb-2">Describe your condition and reason for visit</label>
            <textarea
              value={condition}
              onChange={(e) => setCondition(e.target.value)}
              rows={4}
              placeholder="For example: I am visiting a cardiologist for the first time. I have been feeling chest tightness and breathlessness when climbing stairs for the past two weeks."
              className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary resize-none"
            />
          </div>
          {loading ? (
            <div className="bg-surface-card border border-border rounded-xl p-6"><SkeletonLoader lines={10} /></div>
          ) : (
            <button type="submit" className="w-full py-3 bg-cta text-white font-semibold rounded-lg hover:bg-cta-dark transition-colors">
              Generate My Checklist
            </button>
          )}
        </form>

        {questions.length > 0 && (
          <div className="bg-surface-card border border-border rounded-xl overflow-hidden animate-fade-in">
            <div className="px-6 py-4 border-b border-border">
              <div className="flex items-center justify-between mb-3">
                <h3 className="font-display text-lg font-bold text-text-primary">Your Checklist</h3>
                <span className="text-sm font-medium text-text-secondary">{checkedCount} of {questions.length} asked</span>
              </div>
              <div className="w-full h-2 bg-primary-light rounded-full overflow-hidden">
                <div className="h-full bg-primary rounded-full transition-all duration-300" style={{ width: `${(checkedCount / questions.length) * 100}%` }} />
              </div>
            </div>
            <div className="p-4 space-y-1">
              {questions.map((q, i) => (
                <ChecklistItem key={i} index={i} text={q} checked={checked[i]} onChange={handleCheck} />
              ))}
            </div>
            <div className="px-6 py-4 border-t border-border flex flex-wrap gap-3 items-center justify-between">
              <p className="text-xs text-text-muted">Your progress is saved automatically</p>
              <div className="flex gap-2">
                <button onClick={copyAll} className="px-4 py-2 text-sm font-medium border border-border rounded-lg text-text-secondary hover:bg-surface transition-colors">
                  Copy All Questions
                </button>
                <button onClick={downloadPDF} className="px-4 py-2 text-sm font-medium bg-cta text-white rounded-lg hover:bg-cta-dark transition-colors">
                  Download PDF
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
