import { useState } from 'react';
import ImageUploader from '../components/ImageUploader';
import SkeletonLoader from '../components/SkeletonLoader';
import { useToast } from '../components/Toast';
import { callAI, callAIWithImage, SYSTEM_PROMPTS, buildPrescriptionPrompt } from '../lib/ai';
import { fallbackResponses } from '../lib/fallbacks';
import jsPDF from 'jspdf';

export default function PrescriptionDecoder() {
  const [prescription, setPrescription] = useState('');
  const [imageData, setImageData] = useState(null);
  const [inputMode, setInputMode] = useState('text'); // 'text' | 'image'
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);
  const [expandedIdx, setExpandedIdx] = useState(null);
  const addToast = useToast();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (inputMode === 'text' && !prescription.trim()) { addToast('Please paste your prescription', 'error'); return; }
    if (inputMode === 'image' && !imageData) { addToast('Please upload an image of your prescription', 'error'); return; }
    setLoading(true);
    setResult('');
    try {
      let response;
      if (inputMode === 'image' && imageData) {
        const imagePrompt = prescription.trim()
          ? `This is an image of a medical prescription. Additional context from patient: ${prescription}. Read every medicine from this prescription image and for each one: explain what it is, why it is likely prescribed, how to take it correctly, common side effects, and any warnings. Use very simple language.`
          : 'This is an image of a medical prescription. Read every medicine from this prescription image and for each one: explain what it is, why it is likely prescribed, how to take it correctly, common side effects, and any warnings. Use very simple language. End with the disclaimer: This explanation is for understanding only. Always follow your doctor\'s specific instructions.';
        response = await callAIWithImage(SYSTEM_PROMPTS.prescriptionDecoder, imagePrompt, imageData);
      } else {
        response = await callAI(SYSTEM_PROMPTS.prescriptionDecoder, buildPrescriptionPrompt(prescription));
      }
      setResult(response);
    } catch {
      setResult(fallbackResponses.prescriptionDecoder);
      addToast('Using cached response', 'warning');
    } finally {
      setLoading(false);
    }
  };

  const parseMedicines = (text) => {
    if (!text) return [];
    const sections = text.split(/\*\*(?=.*\*\*)/).filter(Boolean);
    const medicines = [];
    let current = null;
    for (const section of sections) {
      const headerMatch = section.match(/^([^*]+)\*\*/);
      if (headerMatch) {
        const name = headerMatch[1].trim();
        if (name.length < 80) {
          if (current) medicines.push(current);
          current = { name, content: section.replace(/^[^*]+\*\*/, '').trim() };
        } else if (current) {
          current.content += '\n' + section;
        }
      } else if (current) {
        current.content += '\n' + section;
      }
    }
    if (current) medicines.push(current);
    if (medicines.length === 0) return [{ name: 'Prescription Analysis', content: text }];
    return medicines;
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setTextColor(186, 25, 33);
    doc.text('HealthID — Prescription Explanation', 20, 25);
    doc.setFontSize(10);
    doc.setTextColor(26, 6, 8);
    const lines = doc.splitTextToSize(result, 170);
    let y = 45;
    lines.forEach((line) => {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(line, 20, y);
      y += 5;
    });
    doc.setFontSize(8);
    doc.setTextColor(154, 100, 104);
    doc.text('Generated by HealthID — See Clearly. Choose Right.', 20, 285);
    doc.save('HealthID-Prescription-Explained.pdf');
    addToast('Explanation downloaded as PDF');
  };

  const medicines = parseMedicines(result);

  return (
    <div>
      <div className="bg-primary text-white py-10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="font-display text-2xl sm:text-3xl font-bold">Understand Your Prescription</h1>
          <p className="mt-2 text-sm opacity-90">Paste your prescription text or upload a photo. Get plain-language explanations for every medicine.</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        {/* Input mode toggle */}
        <div className="flex gap-1 bg-surface p-1 rounded-lg w-fit">
          <button
            onClick={() => setInputMode('text')}
            className={`px-4 py-2 text-sm font-medium rounded-md transition-colors ${inputMode === 'text' ? 'bg-surface text-primary shadow-sm' : 'text-text-muted hover:text-text-primary'}`}
          >
            <span className="flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Type or Paste
            </span>
          </button>
          <button
            onClick={() => setInputMode('image')}
            className={`px-4 py-2 text-sm font-medium rounded-md transition-colors ${inputMode === 'image' ? 'bg-surface text-primary shadow-sm' : 'text-text-muted hover:text-text-primary'}`}
          >
            <span className="flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              Upload Photo
            </span>
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {inputMode === 'image' && (
            <ImageUploader
              label="Upload a photo of your prescription"
              onImageSelect={setImageData}
            />
          )}

          <textarea
            value={prescription}
            onChange={(e) => setPrescription(e.target.value)}
            rows={inputMode === 'image' ? 3 : 5}
            placeholder={inputMode === 'image'
              ? '(Optional) Add any notes about the prescription, e.g. "prescribed after a stomach infection"'
              : 'For example: Tab Pantoprazole 40mg once daily before food for 14 days, Tab Domperidone 10mg three times daily before food for 7 days, Syrup Sucralfate 10ml twice daily for 14 days'}
            className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary resize-none"
          />

          {loading ? (
            <div className="bg-surface-card border border-border rounded-xl p-6"><SkeletonLoader lines={8} /></div>
          ) : (
            <button type="submit" className="w-full py-3 bg-cta text-white font-semibold rounded-lg hover:bg-cta-dark transition-colors">
              {inputMode === 'image' ? 'Decode Prescription from Image' : 'Decode My Prescription'}
            </button>
          )}
        </form>

        {result && (
          <div className="space-y-3 animate-fade-in">
            {medicines.map((med, i) => (
              <div key={i} className="bg-surface-card border border-border rounded-xl overflow-hidden">
                <button
                  onClick={() => setExpandedIdx(expandedIdx === i ? null : i)}
                  className="w-full px-5 py-4 flex items-center justify-between text-left hover:bg-surface/50 transition-colors"
                >
                  <h4 className="text-sm font-bold text-text-primary">{med.name}</h4>
                  <svg className={`w-5 h-5 text-text-muted transition-transform ${expandedIdx === i ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                {expandedIdx === i && (
                  <div className="px-5 pb-5 border-t border-border pt-4 animate-fade-in">
                    {med.content.split('\n').filter(Boolean).map((line, j) => {
                      const trimmed = line.trim();
                      if (trimmed.startsWith('What it does') || trimmed.startsWith('Why') || trimmed.startsWith('How to') || trimmed.startsWith('Side effects')) {
                        return <h5 key={j} className="text-primary font-semibold text-sm mt-3 mb-1">{trimmed.replace(/:$/, '')}</h5>;
                      }
                      return <p key={j} className="text-sm text-text-secondary leading-relaxed">{trimmed}</p>;
                    })}
                  </div>
                )}
              </div>
            ))}

            <div className="bg-primary-light border border-border rounded-xl p-4">
              <p className="text-xs text-text-secondary">
                <span className="font-semibold">Disclaimer:</span> This explanation is for understanding only. Always follow your doctor's specific instructions and never change your dose without consulting them.
              </p>
            </div>

            <button onClick={downloadPDF} className="w-full py-3 bg-cta text-white font-semibold rounded-lg hover:bg-cta-dark transition-colors">
              Download Full Explanation
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
