import { useState } from 'react';
import { useToast } from './Toast';
import jsPDF from 'jspdf';

export default function AppointmentModal({ doctor, onClose, onSubmit }) {
  const addToast = useToast();
  const [form, setForm] = useState({
    patientName: '', phone: '', email: '', date: '', time: '', reason: '', urgency: 'Low', notes: '',
  });
  const [submitted, setSubmitted] = useState(false);
  const [appointmentResult, setAppointmentResult] = useState(null);

  const availableTimes = doctor.availableSlots?.find(s => s.date === form.date)?.times || [];

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!form.patientName || !form.phone || !form.date || !form.time || !form.reason) {
      addToast('Please fill in all required fields', 'error');
      return;
    }
    const result = {
      id: `APT-${Date.now().toString().slice(-4)}`,
      doctorId: doctor.id,
      doctorName: doctor.name,
      ...form,
      status: 'Pending',
      createdAt: new Date().toISOString().split('T')[0],
    };
    onSubmit(result);
    setAppointmentResult(result);
    setSubmitted(true);
    addToast('Appointment request submitted successfully');
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setTextColor(186, 25, 33);
    doc.text('HealthID — Appointment Confirmation', 20, 25);
    doc.setFontSize(11);
    doc.setTextColor(26, 6, 8);
    doc.text(`Appointment ID: ${appointmentResult.id}`, 20, 45);
    doc.text(`Doctor: ${doctor.name}`, 20, 55);
    doc.text(`Specialisation: ${doctor.specialisation}`, 20, 65);
    doc.text(`Clinic: ${doctor.clinicName}`, 20, 75);
    doc.text(`Date: ${appointmentResult.date}`, 20, 85);
    doc.text(`Time: ${appointmentResult.time}`, 20, 95);
    doc.text(`Patient: ${appointmentResult.patientName}`, 20, 110);
    doc.text(`Phone: ${appointmentResult.phone}`, 20, 120);
    doc.text(`Urgency: ${appointmentResult.urgency}`, 20, 130);
    doc.setFontSize(10);
    doc.setTextColor(92, 26, 30);
    doc.text('Instructions:', 20, 150);
    doc.text('- Please bring a valid photo ID', 20, 160);
    doc.text('- Arrive 10 minutes before your appointment time', 20, 170);
    doc.text('- Bring any previous medical reports or test results', 20, 180);
    doc.setFontSize(8);
    doc.setTextColor(154, 100, 104);
    doc.text('Generated by HealthID — See Clearly. Choose Right.', 20, 270);
    doc.save(`HealthID-Appointment-${appointmentResult.id}.pdf`);
    addToast('Appointment confirmation downloaded');
  };

  if (submitted && appointmentResult) {
    return (
      <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
        <div className="bg-surface-card rounded-xl max-w-md w-full p-6 animate-fade-in" onClick={e => e.stopPropagation()}>
          <div className="text-center mb-6">
            <div className="w-16 h-16 bg-green-50 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h3 className="font-display text-xl font-bold text-text-primary">Appointment Requested</h3>
          </div>
          <div className="space-y-2 text-sm bg-surface p-4 rounded-lg mb-4">
            <p><span className="font-medium text-text-secondary">Appointment ID:</span> {appointmentResult.id}</p>
            <p><span className="font-medium text-text-secondary">Doctor:</span> {doctor.name}</p>
            <p><span className="font-medium text-text-secondary">Date:</span> {appointmentResult.date}</p>
            <p><span className="font-medium text-text-secondary">Time:</span> {appointmentResult.time}</p>
          </div>
          <p className="text-xs text-text-muted mb-4">Please bring a valid photo ID and arrive 10 minutes before your appointment time.</p>
          <div className="flex gap-3">
            <button onClick={downloadPDF} className="flex-1 py-2.5 bg-cta text-white text-sm font-semibold rounded-lg hover:bg-cta-dark transition-colors">
              Download PDF
            </button>
            <button onClick={onClose} className="flex-1 py-2.5 border border-border text-text-secondary text-sm font-semibold rounded-lg hover:bg-surface transition-colors">
              Close
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-surface-card rounded-xl max-w-lg w-full max-h-[90vh] overflow-y-auto animate-fade-in" onClick={e => e.stopPropagation()}>
        <div className="sticky top-0 bg-surface-card border-b border-border px-6 py-4 flex items-center justify-between">
          <h3 className="font-display text-lg font-bold text-text-primary">Request Appointment</h3>
          <button onClick={onClose} className="p-1 rounded-md hover:bg-surface transition-colors">
            <svg className="w-5 h-5 text-text-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          <div className="bg-surface p-3 rounded-lg text-sm">
            <span className="font-medium text-text-primary">{doctor.name}</span>
            <span className="text-text-muted ml-2">{doctor.specialisation}</span>
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">Patient Full Name *</label>
            <input type="text" required value={form.patientName} onChange={e => setForm({...form, patientName: e.target.value})}
              className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary" />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">Phone Number *</label>
            <input type="tel" required value={form.phone} onChange={e => setForm({...form, phone: e.target.value})}
              className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary" />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">Email (optional)</label>
            <input type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})}
              className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-sm font-medium text-text-primary mb-1">Preferred Date *</label>
              <select required value={form.date} onChange={e => setForm({...form, date: e.target.value, time: ''})}
                className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary">
                <option value="">Select date</option>
                {doctor.availableSlots?.map(s => <option key={s.date} value={s.date}>{s.date}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-text-primary mb-1">Preferred Time *</label>
              <select required value={form.time} onChange={e => setForm({...form, time: e.target.value})}
                className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary" disabled={!form.date}>
                <option value="">Select time</option>
                {availableTimes.map(t => <option key={t} value={t}>{t}</option>)}
              </select>
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">Urgency Level</label>
            <select value={form.urgency} onChange={e => setForm({...form, urgency: e.target.value})}
              className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary">
              <option value="Low">Low</option>
              <option value="Moderate">Moderate</option>
              <option value="High">High</option>
              <option value="Emergency">Emergency</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">Reason for Visit *</label>
            <input type="text" required value={form.reason} onChange={e => setForm({...form, reason: e.target.value})}
              className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary" />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">Symptoms or Notes</label>
            <textarea rows={3} value={form.notes} onChange={e => setForm({...form, notes: e.target.value})}
              className="w-full px-3 py-2.5 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary resize-none" />
          </div>
          <button type="submit" className="w-full py-3 bg-cta text-white font-semibold rounded-lg hover:bg-cta-dark transition-colors">
            Submit Appointment Request
          </button>
        </form>
      </div>
    </div>
  );
}
